### ISSUE TITLE
Themes applet won't display in Settings window

### ISSUE THREAD

**Issue by kingogames** [linuxmint/cinnamon-settings-daemon#136]
1) Linux Mint 18 Cinnamon
2) through 5) I can't open the Themes applet in the Settings panel. When I click on it, the Window Title changes to "Themes" but the contents don't display. I can click on other settings applets with no problem. I opened it via the terminal, and here's what I got when I clicked on Themes. I didn't get any errors on the other settings applets in Terminal:

I've uploaded a video of the problem here: https://youtu.be/rvl6nktfhhQ

Terminal output: Loading Themes module
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 549, in button_press
    self.side_view_nav(widget, None, category)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 110, in side_view_nav
    self.go_to_sidepage(cat, filtered_path)
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 123, in go_to_sidepage
    sidePage.build()
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 333, in build
    self.module.on_module_selected()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 100, in on_module_selected
    self.refresh()
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 122, in refresh
    self.refresh_chooser(payload)
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 139, in refresh_chooser
    chooser.add_picture(path, callback, title=theme, id=theme)
  File "/usr/share/cinnamon/cinnamon-settings/bin/SettingsWidgets.py", line 276, in add_picture
    pixbuf = GdkPixbuf.Pixbuf.new_from_file_at_scale(path, -1, self.menu_pictures_size, True)
GLib.Error: rsvg-error-quark: Error writing (1)

**Comment by leigh123linux** [comment]
cinnamon-settings is part of cinnamon so please file your issue there instead.

https://github.com/linuxmint/Cinnamon/issues
