### ISSUE TITLE
csd-automount segfault backtrace

### ISSUE THREAD

**Issue by freddylupin** [linuxmint/cinnamon-settings-daemon#305]
===================================================================
 Info                                                              
===================================================================
           PID: 1198 (csd-automount)
           UID: 1000 (snowden)
           GID: 1000 (snowden)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-09-12 16:26:39 EEST (5 days ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (snowden)
       Boot ID: 25ecb0bff89a4ff9b29dd105090f6a66
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: snowden-HP-Compaq-6000-Pro-MT-PC
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.25ecb0bff89a4ff9b29dd105090f6a66.1198.1599917199000000000000.lz4
       Message: Process 1198 (csd-automount) of user 1000 dumped core.
                
                Stack trace of thread 1198:
                #0  0x0000563c139c5430 n/a (csd-automount + 0x6430)
                linuxmint/linuxmint#1  0x00007f65009e8a28 n/a (libglib-2.0.so.0 + 0x52a28)
                linuxmint/linuxmint#2  0x00007f65009e7e8e g_main_context_dispatch (libglib-2.0.so.0 + 0x51e8e)
                linuxmint/linuxmint#3  0x00007f65009e8240 n/a (libglib-2.0.so.0 + 0x52240)
                linuxmint/linuxmint#4  0x00007f65009e8533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                linuxmint/linuxmint#5  0x00007f650107d37d gtk_main (libgtk-3.so.0 + 0x24e37d)
                linuxmint/linuxmint#6  0x0000563c139c4947 n/a (csd-automount + 0x5947)
                linuxmint/linuxmint#7  0x00007f650068e0b3 __libc_start_main (libc.so.6 + 0x270b3)
                linuxmint/linuxmint#8  0x0000563c139c4aae n/a (csd-automount + 0x5aae)
                
                Stack trace of thread 1214:
                #0  0x00007f650077c96f __GI___poll (libc.so.6 + 0x11596f)
                linuxmint/linuxmint#1  0x00007f65009e81ae n/a (libglib-2.0.so.0 + 0x521ae)
                linuxmint/linuxmint#2  0x00007f65009e82e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                linuxmint/linuxmint#3  0x00007f65009e8331 n/a (libglib-2.0.so.0 + 0x52331)
                linuxmint/linuxmint#4  0x00007f6500a11931 n/a (libglib-2.0.so.0 + 0x7b931)
                linuxmint/linuxmint#5  0x00007f64ffec6609 start_thread (libpthread.so.0 + 0x9609)
                linuxmint/linuxmint#6  0x00007f6500789103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1217:
                #0  0x00007f650077c96f __GI___poll (libc.so.6 + 0x11596f)
                linuxmint/linuxmint#1  0x00007f65009e81ae n/a (libglib-2.0.so.0 + 0x521ae)
                linuxmint/linuxmint#2  0x00007f65009e8533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                linuxmint/linuxmint#3  0x00007f6500c3feda n/a (libgio-2.0.so.0 + 0x11eeda)
                linuxmint/linuxmint#4  0x00007f6500a11931 n/a (libglib-2.0.so.0 + 0x7b931)
                linuxmint/linuxmint#5  0x00007f64ffec6609 start_thread (libpthread.so.0 + 0x9609)
                linuxmint/linuxmint#6  0x00007f6500789103 __clone (libc.so.6 + 0x122103)
                
                Stack trace of thread 1272:
                #0  0x00007f650077c96f __GI___poll (libc.so.6 + 0x11596f)
                linuxmint/linuxmint#1  0x00007f65009e81ae n/a (libglib-2.0.so.0 + 0x521ae)
                linuxmint/linuxmint#2  0x00007f65009e82e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                linuxmint/linuxmint#3  0x00007f64fdd4e99d n/a (libdconfsettings.so + 0xa99d)
                linuxmint/linuxmint#4  0x00007f6500a11931 n/a (libglib-2.0.so.0 + 0x7b931)
                linuxmint/linuxmint#5  0x00007f64ffec6609 start_thread (libpthread.so.0 + 0x9609)
                linuxmint/linuxmint#6  0x00007f6500789103 __clone (libc.so.6 + 0x122103)
===================================================================
 GDB Log                                                           
===================================================================
[New LWP 1198]
[New LWP 1214]
[New LWP 1217]
[New LWP 1272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c139c5430 in ?? ()
[Current thread is 1 (Thread 0x7f64ff5f0a80 (LWP 1198))]

===================================================================
 GDB Backtrace                                                     
===================================================================
[New LWP 1198]
[New LWP 1214]
[New LWP 1217]
[New LWP 1272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c139c5430 in ?? ()
[Current thread is 1 (Thread 0x7f64ff5f0a80 (LWP 1198))]
#0  0x0000563c139c5430 in ?? ()
linuxmint/linuxmint#1  0x00007f65009e8a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#2  0x00007f65009e7e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#3  0x00007f65009e8240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#4  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#5  0x00007f650107d37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
linuxmint/linuxmint#6  0x0000563c139c4947 in ?? ()
linuxmint/linuxmint#7  0x00007f650068e0b3 in __libc_start_main (main=0x563c139c4770, argc=1, argv=0x7ffdda83ee88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdda83ee78) at ../csu/libc-start.c:308
linuxmint/linuxmint#8  0x0000563c139c4aae in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================
[New LWP 1198]
[New LWP 1214]
[New LWP 1217]
[New LWP 1272]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563c139c5430 in ?? ()
[Current thread is 1 (Thread 0x7f64ff5f0a80 (LWP 1198))]

Thread 4 (Thread 0x7f64fdd3a700 (LWP 1272)):
#0  0x00007f650077c96f in __GI___poll (fds=0x563c1425c560, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
linuxmint/linuxmint#1  0x00007f65009e81ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#2  0x00007f65009e82e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#3  0x00007f64fdd4e99d in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
linuxmint/linuxmint#4  0x00007f6500a11931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#5  0x00007f64ffec6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140071731963648, -7564013815811065042, 140728269531038, 140728269531039, 140728269531184, 140071731960960, 7624244686037662510, 7624249310695996206}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
linuxmint/linuxmint#6  0x00007f6500789103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 3 (Thread 0x7f64fe59e700 (LWP 1217)):
#0  0x00007f650077c96f in __GI___poll (fds=0x563c1424db40, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
linuxmint/linuxmint#1  0x00007f65009e81ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#2  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#3  0x00007f6500c3feda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#4  0x00007f6500a11931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#5  0x00007f64ffec6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140071740761856, -7564013815811065042, 140728269531966, 140728269531967, 140728269532112, 140071740759168, 7624248033964669742, 7624249310695996206}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
linuxmint/linuxmint#6  0x00007f6500789103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f64fedaf700 (LWP 1214)):
#0  0x00007f650077c96f in __GI___poll (fds=0x563c1423d240, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
linuxmint/linuxmint#1  0x00007f65009e81ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#2  0x00007f65009e82e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#3  0x00007f65009e8331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#4  0x00007f6500a11931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#5  0x00007f64ffec6609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140071749220096, -7564013815811065042, 140728269531534, 140728269531535, 140728269531680, 140071749217408, 7624246961833458478, 7624249310695996206}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
linuxmint/linuxmint#6  0x00007f6500789103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f64ff5f0a80 (LWP 1198)):
#0  0x0000563c139c5430 in ?? ()
No symbol table info available.
linuxmint/linuxmint#1  0x00007f65009e8a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#2  0x00007f65009e7e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#3  0x00007f65009e8240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#4  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
linuxmint/linuxmint#5  0x00007f650107d37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
linuxmint/linuxmint#6  0x0000563c139c4947 in ?? ()
No symbol table info available.
linuxmint/linuxmint#7  0x00007f650068e0b3 in __libc_start_main (main=0x563c139c4770, argc=1, argv=0x7ffdda83ee88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdda83ee78) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94816027048592, -7564013815811065042, 94816027036288, 140728269532800, 0, 0, 7565075978866604846, 7623812774608583470}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffdda83ee88}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
linuxmint/linuxmint#8  0x0000563c139c4aae in ?? ()
No symbol table info available.
#0  0x0000563c139c5430 in ?? ()
linuxmint/linuxmint#1  0x00007f65009e8a28 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#2  0x00007f65009e7e8e in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#3  0x00007f65009e8240 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#4  0x00007f65009e8533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
linuxmint/linuxmint#5  0x00007f650107d37d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
linuxmint/linuxmint#6  0x0000563c139c4947 in ?? ()
linuxmint/linuxmint#7  0x00007f650068e0b3 in __libc_start_main (main=0x563c139c4770, argc=1, argv=0x7ffdda83ee88, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffdda83ee78) at ../csu/libc-start.c:308
linuxmint/linuxmint#8  0x0000563c139c4aae in ?? ()

**Comment by Kyanite393** [comment]
I have same crash report basically identical...

Ever since install I've been trying to use pre-created Win10.iso USBs and even ext4 USBs, none of the software on LM 20 Cinnamon are working to format, recognize, or utilize ANY USB...

It took me two days just to get LM 20 to install woeusb to attempt to make a new Win 10 usb that will work, I have two HDD the one I just installed LM 20 on then another with a Win 10 install that I screwed up myself while installing LM 20...

So I've been attempting to make a new Win 10 USB Stick cause for some reason my old one just used a week ago isn't being recognized as bootable even if I select it direct from bios boot options... I still just get sent straight to LM 20 with no error or reason as to why my USB is being ignored as a bootable live usb...

The formatter on LM20 takes forever or just plain doesn't work half the time. Even freezes entire machine forcing me to do hard shutdowns...

Disks application also causes freezing etc attempting all of the above via that application. Not just a NTFS issue either as USB apps in LM 20 won't even format a USB to ext4 just hangs forever... WoeUSB the same.
[crash.tar.gz](https://github.com/linuxmint/cinnamon-settings-daemon/files/5287406/crash.tar.gz)

**Comment by Kyanite393** [comment]
Cause I have backups on external USB HDD of that Windows drive... so if my USB stick that I know worked last week is now not working and LM 20 can't even format a USB stick... if it would just recognize or successfully create a new Win 10 USB I can completely restore my Win 10 HDD

**Comment by Kyanite393** [comment]
Also the Win 10 HDD is BRAND NEW and I just fdisk checked the Linux HDD and it had 0 bad sectors

**Comment by MenthaSuaveolens** [comment]
Have the same issue when an 1TB-usb-drive is being plugged in. LM Cinnamon 20
![104836093-a40e8900-58ab-11eb-9a13-697e4710adce](https://user-images.githubusercontent.com/47174957/104854151-60e10400-5905-11eb-90d8-4619b06298ed.png)
[CrashAutoMount.docx](https://github.com/linuxmint/cinnamon-settings-daemon/files/5826689/CrashAutoMount.docx)

**Comment by MenthaSuaveolens** [comment]
Automount falsely warns that ext4-drive has errors (drive is ok)
Mounting 1TB Ext4

[  139.282442] usb 1-1.3.2: new high-speed USB device number 6 using ehci-pci
[  139.443045] usb 1-1.3.2: New USB device found, idVendor=174c, idProduct=5106, bcdDevice=80.00
[  139.443048] usb 1-1.3.2: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  139.443050] usb 1-1.3.2: Product: StoreJet Transcend
[  139.443052] usb 1-1.3.2: Manufacturer: StoreJet Transcend
[  139.443054] usb 1-1.3.2: SerialNumber: S2S6J9BCA09006      
[  139.443449] usb-storage 1-1.3.2:1.0: USB Mass Storage device detected
[  139.443824] scsi host5: usb-storage 1-1.3.2:1.0
[  140.453724] scsi 5:0:0:0: Direct-Access     StoreJet Transcend        0    PQ: 0 ANSI: 6
[  140.454074] sd 5:0:0:0: Attached scsi generic sg2 type 0
[  140.454771] sd 5:0:0:0: [sdc] 1953525168 512-byte logical blocks: (1.00 TB/932 GiB)
[  140.455907] sd 5:0:0:0: [sdc] Write Protect is off
[  140.455910] sd 5:0:0:0: [sdc] Mode Sense: 43 00 00 00
[  140.457043] sd 5:0:0:0: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  140.503980]  sdc: sdc1
[  140.507267] sd 5:0:0:0: [sdc] Attached SCSI disk
[  141.211864] **EXT4-fs (sdc1): warning: mounting fs with errors, running e2fsck is recommended**
[  141.259265] EXT4-fs (sdc1): mounted filesystem with ordered data mode. Opts: (null)

Automount crashes most of the times mounting an NTFS-drive

[  767.501803] usb 1-1.3.2: new high-speed USB device number 10 using ehci-pci
[  767.611403] usb 1-1.3.2: New USB device found, idVendor=1058, idProduct=0748, bcdDevice=10.10
[  767.611406] usb 1-1.3.2: New USB device strings: Mfr=1, Product=2, SerialNumber=5
[  767.611408] usb 1-1.3.2: Product: My Passport 0748
[  767.611409] usb 1-1.3.2: Manufacturer: Western Digital
[  767.611411] usb 1-1.3.2: SerialNumber: 5758343145383143444B3730
[  767.612020] usb-storage 1-1.3.2:1.0: USB Mass Storage device detected
[  767.612557] scsi host5: usb-storage 1-1.3.2:1.0
[  768.630585] scsi 5:0:0:0: Direct-Access     WD       My Passport 0748 1010 PQ: 0 ANSI: 6
[  768.631472] scsi 5:0:0:1: Enclosure         WD       SES Device       1010 PQ: 0 ANSI: 6
[  768.635060] sd 5:0:0:0: Attached scsi generic sg2 type 0
[  768.635395] scsi 5:0:0:1: Attached scsi generic sg3 type 13
[  768.638989] sd 5:0:0:0: [sdc] Spinning up disk...
[  769.653778] .
[  775.630184] scsi 5:0:0:1: Wrong diagnostic page; asked for 1 got 8
[  775.630191] scsi 5:0:0:1: Failed to get diagnostic page 0x1
[  775.630194] scsi 5:0:0:1: Failed to bind enclosure -19
[  775.630635] ready
[  775.631136] sd 5:0:0:0: [sdc] 1953458176 512-byte logical blocks: (1.00 TB/931 GiB)
[  775.632228] sd 5:0:0:0: [sdc] Write Protect is off
[  775.632230] sd 5:0:0:0: [sdc] Mode Sense: 47 00 10 08
[  775.633347] sd 5:0:0:0: [sdc] No Caching mode page found
[  775.633351] sd 5:0:0:0: [sdc] Assuming drive cache: write through
[  775.664112]  sdc: sdc1
[  775.667236] sd 5:0:0:0: [sdc] Attached SCSI disk
[  775.667415] ses 5:0:0:1: Attached Enclosure device
[  778.797946] **csd-automount[1573]: segfault at 8 ip 00005580458b2430 sp 00007ffeb052b3c0 error 4 in csd-automount[5580458b0000+5000]**
[  778.797958] Code: 31 00 00 49 89 c6 e8 bf eb ff ff 4c 89 f6 48 89 c7 31 c0 e8 02 ec ff ff 4c 89 f7 49 89 c4 e8 77 ee ff ff 48 8b 04 24 4c 89 e7 <48> 8b 70 08 e8 57 fc ff ff 4c 89 e7 e8 5f ee ff ff 48 8b 3c 24 e

**Comment by leigh123linux** [comment]
The ext4 filesystem report is normally true, try running this once the drive is umount

```
umount /dev/sdc1
fsck.ext4 -fy /dev/sdc1
```


> Automount falsely warns that ext4-drive has errors (drive is ok)
> Mounting 1TB Ext4

> [ 141.211864] **EXT4-fs (sdc1): warning: mounting fs with errors, running e2fsck is recommended**

**Comment by MenthaSuaveolens** [comment]
Indeed, sudo fsck.ext4 -fy /dev/sdc1 fixed the issue. I normally used the disks-utility and then the repair-command, but it looks that repair-command is doing something else. Thank you leigh123linux
