### ISSUE TITLE
csd-locate-pointer crash core dump

### ISSUE THREAD

**Issue by DaveH1960** [linuxmint/cinnamon-settings-daemon#313]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
ii  cinnamon-settings-daemon                   4.6.4+ulyana                          amd64        daemon handling the Cinnamon session settings

 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 20
 * Graphics hardware *and* driver used
GeForce 8600 GTS
![image](https://user-images.githubusercontent.com/75534824/101247116-56680380-36e5-11eb-90c2-eb623e3d20ee.png)

 * 32 or 64 bit
 ```

**Issue**
Cinnamon crashes at logon when doing a switch user (first logged on user has no issue)

===================================================================
 Info                                                              
===================================================================
           PID: 1825 (csd-locate-poin)
           UID: 1000 (david)
           GID: 1000 (david)
        Signal: 5 (TRAP)
     Timestamp: Sat 2020-12-05 09:43:39 EST (56min ago)
  Command Line: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-locate-pointer
    Executable: /usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-locate-pointer
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (david)
       Boot ID: ee23d91702c445828ea8a8fe9824da47
    Machine ID: b76cc7b1bbdc489e93909d2043031de8
      Hostname: desktop007
       Storage: /var/lib/systemd/coredump/core.csd-locate-poin.1000.ee23d91702c445828ea8a8fe9824da47.1825.1607179419000000000000.lz4
       Message: Process 1825 (csd-locate-poin) of user 1000 dumped core.
                
                Stack trace of thread 1825:
                #0  0x00007f49271b90d5 n/a (libglib-2.0.so.0 + 0x580d5)
                #1  0x00007f49271bbabc g_log_writer_default (libglib-2.0.so.0 + 0x5aabc)
                #2  0x00007f49271b9d17 g_log_structured_array (libglib-2.0.so.0 + 0x58d17)
                #3  0x00007f49271ba744 g_log_structured_standard (libglib-2.0.so.0 + 0x59744)
                #4  0x00007f4927475cea n/a (libgdk-3.so.0 + 0x68cea)
                #5  0x00007f4927482d13 n/a (libgdk-3.so.0 + 0x75d13)
                #6  0x00007f49270650db _XError (libX11.so.6 + 0x410db)
                #7  0x00007f4927061e47 n/a (libX11.so.6 + 0x3de47)
                #8  0x00007f4927061ee5 n/a (libX11.so.6 + 0x3dee5)
                #9  0x00007f4927062832 _XEventsQueued (libX11.so.6 + 0x3e832)
                #10 0x00007f4927054171 XPending (libX11.so.6 + 0x30171)
                #11 0x00007f492747d183 n/a (libgdk-3.so.0 + 0x70183)
                #12 0x00007f49271b2be1 g_main_context_check (libglib-2.0.so.0 + 0x51be1)
                #13 0x00007f49271b3152 n/a (libglib-2.0.so.0 + 0x52152)
                #14 0x00007f49271b3533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #15 0x00007f492776037d gtk_main (libgtk-3.so.0 + 0x24e37d)
                #16 0x00005643654aeeef n/a (csd-locate-pointer + 0x3eef)
                #17 0x00007f4926d080b3 __libc_start_main (libc.so.6 + 0x270b3)
                #18 0x00005643654af09e n/a (csd-locate-pointer + 0x409e)
                
                Stack trace of thread 1939:
                #0  0x00007f4926df6aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f49271b31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f49271b32e3 g_main_context_iteration (libglib-2.0.so.0 + 0x522e3)
                #3  0x00007f49271b3331 n/a (libglib-2.0.so.0 + 0x52331)
                #4  0x00007f49271dc931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f4926656609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f4926e03293 __clone (libc.so.6 + 0x122293)
                
                Stack trace of thread 1940:
                #0  0x00007f4926df6aff __GI___poll (libc.so.6 + 0x115aff)
                #1  0x00007f49271b31ae n/a (libglib-2.0.so.0 + 0x521ae)
                #2  0x00007f49271b3533 g_main_loop_run (libglib-2.0.so.0 + 0x52533)
                #3  0x00007f4926a03eda n/a (libgio-2.0.so.0 + 0x11eeda)
                #4  0x00007f49271dc931 n/a (libglib-2.0.so.0 + 0x7b931)
                #5  0x00007f4926656609 start_thread (libpthread.so.0 + 0x9609)
                #6  0x00007f4926e03293 __clone (libc.so.6 + 0x122293)
===================================================================
 GDB Log                                                           
===================================================================

warning: core file may not match specified executable file.
[New LWP 1825]
[New LWP 1939]
[New LWP 1940]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-locate-pointer'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f49271b90d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f4925cd1a80 (LWP 1825))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: core file may not match specified executable file.
[New LWP 1825]
[New LWP 1939]
[New LWP 1940]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-locate-pointer'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f49271b90d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f4925cd1a80 (LWP 1825))]
#0  0x00007f49271b90d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f49271bbabc in g_log_writer_default () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f49271b9d17 in g_log_structured_array () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f49271ba744 in g_log_structured_standard () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f4927475cea in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f4927482d13 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f49270650db in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f4927061e47 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f4927061ee5 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f4927062832 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f4927054171 in XPending () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f492747d183 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f49271b2be1 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f49271b3152 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f49271b3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f492776037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00005643654aeeef in ?? ()
#17 0x00007f4926d080b3 in __libc_start_main (main=0x5643654aee40, argc=1, argv=0x7fff50fbc4e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff50fbc4d8) at ../csu/libc-start.c:308
#18 0x00005643654af09e in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: core file may not match specified executable file.
[New LWP 1825]
[New LWP 1939]
[New LWP 1940]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/lib/x86_64-linux-gnu/cinnamon-settings-daemon/csd-locate-pointer'.
Program terminated with signal SIGTRAP, Trace/breakpoint trap.
#0  0x00007f49271b90d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f4925cd1a80 (LWP 1825))]

Thread 3 (Thread 0x7f4924ee5700 (LWP 1940)):
#0  0x00007f4926df6aff in __GI___poll (fds=0x564366f06fd0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f49271b31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f49271b3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f4926a03eda in ?? () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f49271dc931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f4926656609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139952128939776, 6114954627881120181, 140734552062238, 140734552062239, 140734552062384, 139952128937088, -6174744011157524043, -6174749415650217547}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f4926e03293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 2 (Thread 0x7f49256e6700 (LWP 1939)):
#0  0x00007f4926df6aff in __GI___poll (fds=0x564366ef46e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        resultvar = 18446744073709551100
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f49271b31ae in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f49271b32e3 in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f49271b3331 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f49271dc931 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f4926656609 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139952137332480, 6114954627881120181, 140734552061806, 140734552061807, 140734552061952, 139952137329792, -6174747310229278283, -6174749415650217547}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#6  0x00007f4926e03293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

Thread 1 (Thread 0x7f4925cd1a80 (LWP 1825)):
#0  0x00007f49271b90d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#1  0x00007f49271bbabc in g_log_writer_default () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f49271b9d17 in g_log_structured_array () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f49271ba744 in g_log_structured_standard () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f4927475cea in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#5  0x00007f4927482d13 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#6  0x00007f49270650db in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#7  0x00007f4927061e47 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#8  0x00007f4927061ee5 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#9  0x00007f4927062832 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#10 0x00007f4927054171 in XPending () from /usr/lib/x86_64-linux-gnu/libX11.so.6
No symbol table info available.
#11 0x00007f492747d183 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
#12 0x00007f49271b2be1 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#13 0x00007f49271b3152 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#14 0x00007f49271b3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#15 0x00007f492776037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#16 0x00005643654aeeef in ?? ()
No symbol table info available.
#17 0x00007f4926d080b3 in __libc_start_main (main=0x5643654aee40, argc=1, argv=0x7fff50fbc4e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff50fbc4d8) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {94847462216528, 6114954627881120181, 94847462207600, 140734552065248, 0, 0, -6115308703626546763, -6174747947751558731}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7fff50fbc4e8}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#18 0x00005643654af09e in ?? ()
No symbol table info available.
#0  0x00007f49271b90d5 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f49271bbabc in g_log_writer_default () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f49271b9d17 in g_log_structured_array () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f49271ba744 in g_log_structured_standard () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f4927475cea in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#5  0x00007f4927482d13 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#6  0x00007f49270650db in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#7  0x00007f4927061e47 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#8  0x00007f4927061ee5 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007f4927062832 in _XEventsQueued () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007f4927054171 in XPending () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007f492747d183 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#12 0x00007f49271b2be1 in g_main_context_check () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f49271b3152 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f49271b3533 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f492776037d in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00005643654aeeef in ?? ()
#17 0x00007f4926d080b3 in __libc_start_main (main=0x5643654aee40, argc=1, argv=0x7fff50fbc4e8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff50fbc4d8) at ../csu/libc-start.c:308
#18 0x00005643654af09e in ?? ()

**Steps to reproduce**
Logon to one account and then do switch user 

**Expected behaviour**
No crash

**Other information**

**Comment by ItzSwirlz** [comment]
Install the debug symbols, then if the crash reoccurs then give it to us
