### ISSUE TITLE
External USB Hdd Won't load

### ISSUE THREAD

**Issue by Daicarno** [linuxmint/cinnamon-settings-daemon#397]
```
 * csd version ('dpkg --list | grep cinnamon-settings-daemon' in Mint/Ubuntu)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 ```

**Issue**External USB Hdd / dvd player won't load, Mint 22 Wilma

**Steps to reproduce**
Appears according to forums to be a kernel issue

**Expected behaviour**
Not recognised By Mint Wilma

**Other information** "Error mounting /dev/sdb1, missiingc odepage or helper program, or other error.

Hdd file system is NTFS

**Comment by Daicarno** [comment]
===================================================================
 Info                                                              
===================================================================
           PID: 1488 (csd-automount)
           UID: 1000 (evan)
           GID: 1000 (evan)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-08-26 09:40:52 IST (3 days ago)
  Command Line: /usr/bin/csd-automount
    Executable: /usr/libexec/csd-automount
 Control Group: /user.slice/user-1000.slice/session-c2.scope
          Unit: session-c2.scope
         Slice: user-1000.slice
       Session: c2
     Owner UID: 1000 (evan)
       Boot ID: 8bd246cc6bff475fae69359c1cb8104e
    Machine ID: 2d6e9914d31e403598b993ebabed5bec
      Hostname: evan-HP-Laptop-14s-dq0xxx
       Storage: /var/lib/systemd/coredump/core.csd-automount.1000.8bd246cc6bff475fae69359c1cb8104e.1488.1724661652000000.zst (present)
  Size on Disk: 1.0M
       Message: Process 1488 (csd-automount) of user 1000 dumped core.
                
                Module libzstd.so.1 from deb libzstd-1.5.5+dfsg2-2build1.1.amd64
                Module libsystemd.so.0 from deb systemd-255.4-1ubuntu8.4.amd64
                Stack trace of thread 1488:
                #0  0x0000582c790c52a8 n/a (csd-automount + 0x62a8)
                #1  0x00007f43d3de22fa g_closure_invoke (libgobject-2.0.so.0 + 0x152fa)
                #2  0x00007f43d3e1190c n/a (libgobject-2.0.so.0 + 0x4490c)
                #3  0x00007f43d3e02591 n/a (libgobject-2.0.so.0 + 0x35591)
                #4  0x00007f43d3e027c1 g_signal_emit_valist (libgobject-2.0.so.0 + 0x357c1)
                #5  0x00007f43d3e02883 g_signal_emit (libgobject-2.0.so.0 + 0x35883)
                #6  0x00007f43d3f4ec4b n/a (libgio-2.0.so.0 + 0x11ec4b)
                #7  0x00007f43d3f38a30 n/a (libgio-2.0.so.0 + 0x108a30)
                #8  0x00007f43d3ce148e n/a (libglib-2.0.so.0 + 0x5d48e)
                #9  0x00007f43d3d40717 n/a (libglib-2.0.so.0 + 0xbc717)
                #10 0x00007f43d3ce1f77 g_main_loop_run (libglib-2.0.so.0 + 0x5df77)
                #11 0x00007f43d41feb45 gtk_main (libgtk-3.so.0 + 0x1feb45)
                #12 0x0000582c790c48d3 n/a (csd-automount + 0x58d3)
                #13 0x00007f43d382a1ca __libc_start_call_main (libc.so.6 + 0x2a1ca)
                #14 0x00007f43d382a28b __libc_start_main_impl (libc.so.6 + 0x2a28b)
                #15 0x0000582c790c4ae5 n/a (csd-automount + 0x5ae5)
                
                Stack trace of thread 1517:
                #0  0x00007f43d391b4cd __GI___poll (libc.so.6 + 0x11b4cd)
                #1  0x00007f43d3d4066e n/a (libglib-2.0.so.0 + 0xbc66e)
                #2  0x00007f43d3ce0a53 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca53)
                #3  0x00007f43d3ce0aa9 n/a (libglib-2.0.so.0 + 0x5caa9)
                #4  0x00007f43d3d0fc82 n/a (libglib-2.0.so.0 + 0x8bc82)
                #5  0x00007f43d389ca94 start_thread (libc.so.6 + 0x9ca94)
                #6  0x00007f43d3929c3c __clone3 (libc.so.6 + 0x129c3c)
                
                Stack trace of thread 1581:
                #0  0x00007f43d391b4cd __GI___poll (libc.so.6 + 0x11b4cd)
                #1  0x00007f43d3d4066e n/a (libglib-2.0.so.0 + 0xbc66e)
                #2  0x00007f43d3ce0a53 g_main_context_iteration (libglib-2.0.so.0 + 0x5ca53)
                #3  0x00007f43d2a02595 n/a (libdconfsettings.so + 0x7595)
                #4  0x00007f43d3d0fc82 n/a (libglib-2.0.so.0 + 0x8bc82)
                #5  0x00007f43d389ca94 start_thread (libc.so.6 + 0x9ca94)
                #6  0x00007f43d3929c3c __clone3 (libc.so.6 + 0x129c3c)
                
                Stack trace of thread 1516:
                #0  0x00007f43d392725d syscall (libc.so.6 + 0x12725d)
                #1  0x00007f43d3d3a40d g_cond_wait (libglib-2.0.so.0 + 0xb640d)
                #2  0x00007f43d3cab52b n/a (libglib-2.0.so.0 + 0x2752b)
                #3  0x00007f43d3d13043 n/a (libglib-2.0.so.0 + 0x8f043)
                #4  0x00007f43d3d0fc82 n/a (libglib-2.0.so.0 + 0x8bc82)
                #5  0x00007f43d389ca94 start_thread (libc.so.6 + 0x9ca94)
                #6  0x00007f43d3929c3c __clone3 (libc.so.6 + 0x129c3c)
                
                Stack trace of thread 1522:
                #0  0x00007f43d391b4cd __GI___poll (libc.so.6 + 0x11b4cd)
                #1  0x00007f43d3d4066e n/a (libglib-2.0.so.0 + 0xbc66e)
                #2  0x00007f43d3ce1f77 g_main_loop_run (libglib-2.0.so.0 + 0x5df77)
                #3  0x00007f43d3f4a422 n/a (libgio-2.0.so.0 + 0x11a422)
                #4  0x00007f43d3d0fc82 n/a (libglib-2.0.so.0 + 0x8bc82)
                #5  0x00007f43d389ca94 start_thread (libc.so.6 + 0x9ca94)
                #6  0x00007f43d3929c3c __clone3 (libc.so.6 + 0x129c3c)
                
                Stack trace of thread 25874:
                #0  0x00007f43d3929c2d __clone3 (libc.so.6 + 0x129c2d)
                #1  0x00007f43d389c540 create_thread (libc.so.6 + 0x9c540)
                #2  0x00007f43cf9ff950 n/a (n/a + 0x0)
                #3  0x00007f43d3dcbf70 n/a (libglib-2.0.so.0 + 0x147f70)
                #4  0x0000000000000004 n/a (n/a + 0x0)
                ELF object binary architecture: AMD x86-64
===================================================================
 GDB Log                                                           
===================================================================

warning: Can't open file /usr/lib/x86_64-linux-gnu/libicudata.so.74.2 (deleted) during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libicuuc.so.74.2 (deleted) during file-backed mapping note processing
[New LWP 1488]
[New LWP 1517]
[New LWP 1581]
[New LWP 1516]
[New LWP 1522]
[New LWP 25874]

warning: Build-id of /lib/x86_64-linux-gnu/libmount.so.1 does not match core file.

warning: Build-id of /lib/x86_64-linux-gnu/libblkid.so.1 does not match core file.

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk-3.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgobject-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libglib-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgmodule-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libxapp-gtk3-module.so

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libxapp.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgnomekbdui.so.8

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgnomekbd.so.8

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000582c790c52a8 in ?? ()
[Current thread is 1 (Thread 0x7f43d2a0aa80 (LWP 1488))]

===================================================================
 GDB Backtrace                                                     
===================================================================

warning: Can't open file /usr/lib/x86_64-linux-gnu/libicudata.so.74.2 (deleted) during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libicuuc.so.74.2 (deleted) during file-backed mapping note processing
[New LWP 1488]
[New LWP 1517]
[New LWP 1581]
[New LWP 1516]
[New LWP 1522]
[New LWP 25874]

warning: Build-id of /lib/x86_64-linux-gnu/libmount.so.1 does not match core file.

warning: Build-id of /lib/x86_64-linux-gnu/libblkid.so.1 does not match core file.

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk-3.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgobject-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libglib-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgmodule-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libxapp-gtk3-module.so

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libxapp.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgnomekbdui.so.8

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgnomekbd.so.8

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000582c790c52a8 in ?? ()
[Current thread is 1 (Thread 0x7f43d2a0aa80 (LWP 1488))]
#0  0x0000582c790c52a8 in ?? ()
#1  0x00007f43d3de22fa in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007f43d3e1190c in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007f43d3e02591 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007f43d3e027c1 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f43d3e02883 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f43d3f4ec4b in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f43d3f38a30 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f43d3ce148e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007f43d3d40717 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007f43d3ce1f77 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f43d41feb45 in gtk_main () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x0000582c790c48d3 in ?? ()
#13 0x00007f43d382a1ca in __libc_start_call_main (main=main@entry=0x582c790c45c0, argc=argc@entry=1, argv=argv@entry=0x7ffda87c31b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#14 0x00007f43d382a28b in __libc_start_main_impl (main=0x582c790c45c0, argc=1, argv=0x7ffda87c31b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffda87c31a8) at ../csu/libc-start.c:360
#15 0x0000582c790c4ae5 in ?? ()

===================================================================
 GDB Backtrace (all threads)                                       
===================================================================

warning: Can't open file /usr/lib/x86_64-linux-gnu/libicudata.so.74.2 (deleted) during file-backed mapping note processing

warning: Can't open file /usr/lib/x86_64-linux-gnu/libicuuc.so.74.2 (deleted) during file-backed mapping note processing
[New LWP 1488]
[New LWP 1517]
[New LWP 1581]
[New LWP 1516]
[New LWP 1522]
[New LWP 25874]

warning: Build-id of /lib/x86_64-linux-gnu/libmount.so.1 does not match core file.

warning: Build-id of /lib/x86_64-linux-gnu/libblkid.so.1 does not match core file.

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk-3.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgobject-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libglib-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgmodule-2.0.so.0

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libcap.so.2

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlidec.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libbrotlicommon.so.1

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libxapp-gtk3-module.so

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libxapp.so.1

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgnomekbdui.so.8

warning: could not find '.gnu_debugaltlink' file for /lib/x86_64-linux-gnu/libgnomekbd.so.8

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so

warning: could not find '.gnu_debugaltlink' file for /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/csd-automount'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000582c790c52a8 in ?? ()
[Current thread is 1 (Thread 0x7f43d2a0aa80 (LWP 1488))]

Thread 6 (Thread 0x7f43cd2006c0 (LWP 25874)):
#0  clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:62
No locals.
#1  0x0000000000000000 in ?? ()
No symbol table info available.

Thread 5 (Thread 0x7f43ce6006c0 (LWP 1522)):
#0  0x00007f43d391b4cd in __GI___poll (fds=0x7f43bc000b90, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = 1
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f43d3d4066e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f43d3ce1f77 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f43d3f4a422 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#4  0x00007f43d3d0fc82 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f43d389ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139929201936064, -1447449073353267594, 139929201936064, -120, 11, 140727430159504, -1447449073374239114, -1447455308175284618}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f43d3929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.

Thread 4 (Thread 0x7f43cfa006c0 (LWP 1516)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
No locals.
#1  0x00007f43d3d3a40d in g_cond_wait () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f43d3cab52b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f43d3d13043 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f43d3d0fc82 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f43d389ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139929222907584, -1447446324574198154, 139929222907584, -120, 0, 140727430159360, -1447446324595169674, -1447455308175284618}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f43d3929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.

Thread 3 (Thread 0x7f43cdc006c0 (LWP 1581)):
#0  0x00007f43d391b4cd in __GI___poll (fds=0x7f43b4000b90, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f43d3d4066e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f43d3ce0a53 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f43d2a02595 in ?? () from /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
No symbol table info available.
#4  0x00007f43d3d0fc82 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f43d389ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139929191450304, -1447441651649780106, 139929191450304, -120, 17, 140727430162288, -1447441651670751626, -1447455308175284618}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f43d3929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.

Thread 2 (Thread 0x7f43cf0006c0 (LWP 1517)):
#0  0x00007f43d391b4cd in __GI___poll (fds=0x582c79e35bd0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
        sc_ret = -516
        sc_cancel_oldtype = 0
        sc_ret = <optimized out>
#1  0x00007f43d3d4066e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007f43d3ce0a53 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007f43d3ce0aa9 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007f43d3d0fc82 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007f43d389ca94 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
        ret = <optimized out>
        pd = <optimized out>
        out = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139929212421824, -1447447698963732874, 139929212421824, -120, 0, 140727430159152, -1447447698984704394, -1447455308175284618}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#6  0x00007f43d3929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
No locals.

Thread 1 (Thread 0x7f43d2a0aa80 (LWP 1488)):
#0  0x0000582c790c52a8 in ?? ()
No symbol table info available.
#1  0x00007f43d3de22fa in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#2  0x00007f43d3e1190c in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#3  0x00007f43d3e02591 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#4  0x00007f43d3e027c1 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#5  0x00007f43d3e02883 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007f43d3f4ec4b in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#7  0x00007f43d3f38a30 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#8  0x00007f43d3ce148e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#9  0x00007f43d3d40717 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#10 0x00007f43d3ce1f77 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#11 0x00007f43d41feb45 in gtk_main () from /lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#12 0x0000582c790c48d3 in ?? ()
No symbol table info available.
#13 0x00007f43d382a1ca in __libc_start_call_main (main=main@entry=0x582c790c45c0, argc=argc@entry=1, argv=argv@entry=0x7ffda87c31b8) at ../sysdeps/nptl/libc_start_call_main.h:58
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140727430164920, -1543207471973177738, 1, 0, 96948032677824, 139929306390528, -1543207471987857802, -1447455354560616842}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x1, 0x7ffda87c31b0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1}}}
        not_first_call = <optimized out>
#14 0x00007f43d382a28b in __libc_start_main_impl (main=0x582c790c45c0, argc=1, argv=0x7ffda87c31b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffda87c31a8) at ../csu/libc-start.c:360
No locals.
#15 0x0000582c790c4ae5 in ?? ()
No symbol table info available.
#0  0x0000582c790c52a8 in ?? ()
#1  0x00007f43d3de22fa in g_closure_invoke () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007f43d3e1190c in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00007f43d3e02591 in ?? () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007f43d3e027c1 in g_signal_emit_valist () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007f43d3e02883 in g_signal_emit () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f43d3f4ec4b in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f43d3f38a30 in ?? () from /lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f43d3ce148e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007f43d3d40717 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007f43d3ce1f77 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007f43d41feb45 in gtk_main () from /lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x0000582c790c48d3 in ?? ()
#13 0x00007f43d382a1ca in __libc_start_call_main (main=main@entry=0x582c790c45c0, argc=argc@entry=1, argv=argv@entry=0x7ffda87c31b8) at ../sysdeps/nptl/libc_start_call_main.h:58
#14 0x00007f43d382a28b in __libc_start_main_impl (main=0x582c790c45c0, argc=1, argv=0x7ffda87c31b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffda87c31a8) at ../csu/libc-start.c:360
#15 0x0000582c790c4ae5 in ?? ()
