### ISSUE TITLE
XInput usage leads to c-s-d crash. 

### ISSUE THREAD

**Issue by vladimir-didenko** [linuxmint/cinnamon-settings-daemon#9]
Follow commit 'fix media keys for gtk>3.7.8 '

https://github.com/linuxmint/cinnamon-settings-daemon/commit/6c1f75c1a617dd11b56731594907da3577d1d556

leads to c-s-d crashes. Usually I have follow backtrace in core file

```
#0  0x00007faafc418d5f in gtk_status_icon_get_x11_window_id () from /usr/lib64/libgtk-3.so.0.800.2
#1  0x00007faada13b8bc in gkbd_status_filter_x_evt (xev=0x7fff425fd650, event=<optimized out>) at gkbd-status.c:474
#2  0x00007faafa8fd9ab in gdk_event_apply_filters () from /usr/lib64/libgdk-3.so.0.800.2
#3  0x00007faafa8fdd3d in gdk_event_source_translate_event () from /usr/lib64/libgdk-3.so.0.800.2
#4  0x00007faafa8fe081 in _gdk_x11_display_queue_events () from /usr/lib64/libgdk-3.so.0.800.2
#5  0x00007faafa8bfee3 in gdk_display_get_event () from /usr/lib64/libgdk-3.so.0.800.2
#6  0x00007faafa8fe14b in gdk_event_source_dispatch () from /usr/lib64/libgdk-3.so.0.800.2
#7  0x00007faafb8ddc45 in g_main_dispatch (context=0x666f90) at gmain.c:3054
#8  g_main_context_dispatch (context=context@entry=0x666f90) at gmain.c:3630
#9  0x00007faafb8ddf88 in g_main_context_iterate (context=0x666f90, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3701
#10 0x00007faafb8de3ea in g_main_loop_run (loop=0x7ac3c0) at gmain.c:3895
#11 0x00007faafc3657f4 in gtk_main () from /usr/lib64/libgtk-3.so.0.800.2
#12 0x0000000000403815 in main (argc=1, argv=0x7fff425fd9e8) at main.c:568
```

But sometimes I have another backtraces e.g.

```
#0  0x00007ff4613680b8 in gdk_error_trap_pop_internal () from /usr/lib64/libgdk-3.so.0.800.2
#1  0x00007ff461368131 in gdk_error_trap_pop () from /usr/lib64/libgdk-3.so.0.800.2
#2  0x00007ff431574802 in init_kbd (manager=0x670470) at csd-media-keys-manager.c:550
#3  start_media_keys_idle_cb (manager=0x670470) at csd-media-keys-manager.c:2071
#4  0x00007ff462382c45 in g_main_dispatch (context=0x6688e0) at gmain.c:3054
#5  g_main_context_dispatch (context=context@entry=0x6688e0) at gmain.c:3630
#6  0x00007ff462382f88 in g_main_context_iterate (context=0x6688e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3701
#7  0x00007ff4623833ea in g_main_loop_run (loop=0x7af760) at gmain.c:3895
#8  0x00007ff462e0a7f4 in gtk_main () from /usr/lib64/libgtk-3.so.0.800.2
#9  0x0000000000403815 in main (argc=1, argv=0x7fffe19e3a78) at main.c:568
```

or

```
#0  magazine_chain_pop_head (magazine_chunks=0x60d660) at gslice.c:532
#1  thread_memory_magazine1_alloc (tmem=<optimized out>, ix=0) at gslice.c:835
#2  g_slice_alloc (mem_size=mem_size@entry=16) at gslice.c:994
#3  0x00007f31fa29bff1 in g_error_new_valist (domain=578, code=2, format=0x7f31fa8f493d "GDBus.Error:%s: %s", args=args@entry=0x7fff96a5ebb8) at gerror.c:393
#4  0x00007f31fa29c111 in g_error_new (domain=<optimized out>, code=<optimized out>, format=format@entry=0x7f31fa8f493d "GDBus.Error:%s: %s") at gerror.c:427
#5  0x00007f31fa89e0b3 in g_dbus_error_new_for_dbus_error (dbus_error_name=0x7f31e800e110 "org.freedesktop.DBus.Error.ServiceUnknown", 
dbus_error_message=0x933ed0 "The name org.cinnamon.SettingsDaemon was not provided by any .service files") at gdbuserror.c:619
#6  0x00007f31fa89e598 in g_dbus_error_set_dbus_error (error=error@entry=0x7fff96a5ee40, dbus_error_name=dbus_error_name@entry=0x7f31e800e110 "org.freedesktop.DBus.Error.ServiceUnknown", 
dbus_error_message=<optimized out>, format=<optimized out>) at gdbuserror.c:684
#7  0x00007f31fa8abb6b in g_dbus_message_to_gerror (message=message@entry=0x7bfcf0, error=error@entry=0x7fff96a5ee40) at gdbusmessage.c:3276
#8  0x00007f31fa89fa6d in decode_method_reply (reply=0x7bfcf0, method_name=0x7d4320 "org.freedesktop.DBus.StartServiceByName", reply_type=0x7d1810, out_fd_list=0x7d48c8, error=0x7fff96a5ee40)
at gdbusconnection.c:5252
#9  0x00007f31fa8a4bfe in g_dbus_connection_call_done (source=<optimized out>, result=<optimized out>, user_data=0x7d48a0) at gdbusconnection.c:5327
#10 0x00007f31fa853557 in g_simple_async_result_complete (simple=0x7c3630) at gsimpleasyncresult.c:777
#11 0x00007f31fa853659 in complete_in_idle_cb (data=<optimized out>) at gsimpleasyncresult.c:789
#12 0x00007f31fa2afc45 in g_main_dispatch (context=0x666f90) at gmain.c:3054
#13 g_main_context_dispatch (context=context@entry=0x666f90) at gmain.c:3630
#14 0x00007f31fa2aff88 in g_main_context_iterate (context=0x666f90, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3701
#15 0x00007f31fa2b03ea in g_main_loop_run (loop=0x7bfa00) at gmain.c:3895
#16 0x00007f31fad377f4 in gtk_main () from /usr/lib64/libgtk-3.so.0.800.2
#17 0x0000000000403815 in main (argc=1, argv=0x7fff96a5f0d8) at main.c:568
```

**Comment by leigh123linux** [comment]
This was fixed a long time ago.
